#-------------服务中心地址-------------
eureka_uri: http://139.9.201.224/eureka

server:
  port: 15675

spring:
  application:
    name: config-client

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_uri}/eureka/


---
server:
  port: 15676
spring:
  profiles: dev
hello: Test:121212121212Hello My World from port:${server.port}