#刷新地址（更改需重启后生效）


server:
  port: 9030

spring:
  application:
    name: config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://139.9.201.224:9010/eureka/


---
server:
  port: 9031
spring:
  profiles: dev
hello: Test:----Hello My World from port:${server.port}